### ISSUE TITLE
Errors while running export, backup & restore.

### ISSUE THREAD

**Issue by starit1977** [crate/elasticsearch-inout-plugin#44]
Please help, i'm getting errors while using this pluging.

During restore - 

local@pldsvv-07:/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch/nodes/0/dump$ curl -X POST 'http://localhost:9200/test/_restore'
{"imports":[{"node_id":"CPLS3RSJQ_Ks-Wky0iZiGQ","took":42846,"imported_files":[{"file_name":"/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch5/nodes/0/dump/elasticsearch_test_2.json.gz","successes":54751,"failures":0},{"file_name":"/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch5/nodes/0/dump/elasticsearch_test_4.json.gz","successes":54735,"failures":0},{"file_name":"/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch5/nodes/0/dump/elasticsearch_test_3.json.gz","successes":54767,"failures":0},{"file_name":"/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch5/nodes/0/dump/elasticsearch_test_0.json.gz","successes":54792,"failures":0},{"file_name":"/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch5/nodes/0/dump/elasticsearch_test_1.json.gz","successes":54736,"failures":0}]}],"failures":[{"node_id":"lfx_THIqQQCc8K7O9BV80A","reason":"org.elasticsearch.action.FailedNodeException: Failed node [lfx_THIqQQCc8K7O9BV80A]; org.elasticsearch.transport.RemoteTransportException: [52][inet[/10.3.176.22:9300]][el-crate-restore/n]; org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [el-crate-restore/n]"},{"node_id":"o9CeDxCZT7KX3dvLueHyng","reason":"org.elasticsearch.action.FailedNodeException: Failed node [o9CeDxCZT7KX3dvLueHyng]; org.elasticsearch.transport.RemoteTransportException: [51][inet[/10.3.176.140:9300]][el-crate-restore/n]; org.elasticsearch.transport.ActionNotFoundTransportException: No handler for action [el-crate-restore/n]"}]}local@pldsvv-07:/var/elasticsearch/elasticsearch-0.90.5/data/elasticsearch/nodes/0/dump$

During export - 
curl -X POST 'http://localhost:9200/test/_export' -d '{
    "fields": ["_id", "_source", "_version", "_index", "_type"],
    "output_file": "/tmp/es-data/dump-${index}-${shard}"
}
'
[2013-09-18 17:52:08,651][WARN ][http.netty               ] [53] Caught exception while handling client http traffic, closing connection [id: 0x42276f0d, /127.0.0.1:54324 => /127.0.0.1:9200]
java.lang.NoSuchMethodError: org.elasticsearch.rest.action.support.RestActions.splitIndices(Ljava/lang/String;)[Ljava/lang/String;
        at crate.elasticsearch.rest.action.admin.export.RestExportAction.handleRequest(RestExportAction.java:55)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:159)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:142)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:291)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:43)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
curl: (52) Empty reply from server

During backup or dump - 

 curl -X POST 'http://10.3.176.133:9200/test/_dump'
[2013-09-18 17:59:17,532][WARN ][http.netty               ] [53] Caught exception while handling client http traffic, closing connection [id: 0x39baca11, /10.3.176.133:56987 => /10.3.176.133:9200]
java.lang.NoSuchMethodError: org.elasticsearch.rest.action.support.RestActions.splitIndices(Ljava/lang/String;)[Ljava/lang/String;
        at crate.elasticsearch.rest.action.admin.export.RestExportAction.handleRequest(RestExportAction.java:55)
        at org.elasticsearch.rest.RestController.executeHandler(RestController.java:159)
        at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:142)
        at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
        at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
        at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:291)
        at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:43)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
        at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:724)
curl: (52) Empty reply from server

**Comment by mfussenegger** [comment]
Hi,

the first error seems to indicate that you don't have the plugin installed on
all the nodes.

the second error is caused because `.RestActions.splitIndices(` got removed in
0.90.4 or 0.90.5 and we haven't updated the plugin yet.

**Comment by starit1977** [comment]
thanks.

does that mean i can't use the plug in - for elasticsearch version 0.90.4 or 0.90.5?
I was using elasticsearch 0.90.3 and with the same plug in - i was getting out of heap memory error, so i upgraded to elasticsearch version 0.90.5.

which version of elasticsearch should i be using for this plug in to work correctly?

thanks
pranav.

**Comment by starit1977** [comment]
The out of heap error i was getting ( i have logged on this site as well Reference # 42).
I was told to upgrade to elasticsearch version 0.90.5 in order to get rid of the error.

Thanks
Pranav.

**Comment by starit1977** [comment]
Hey guys,

Appreciate if any one can provide any feedback on this? I'm trying other plug ins, but this plug in has got really good stuff and i really want it to use. But the errors above are restricting me from using it for my project.

Thanks again

Pranav.

**Comment by starit1977** [comment]
i have posted counter questions on this, appreciate if someone can take a look.

**Comment by mfussenegger** [comment]
ES 0.90.2 with 0.5.0 of the plugin works probably best for now.

If you're using 0.90.3 you'll probably have to increase the heap memory size.

For 0.90.4 and 0.90.5 you'll have to be patient a little bit longer. They got
just released a couple of days ago and it takes a bit time for us to upgrade.

**Comment by starit1977** [comment]
Thanks a lot. I will try them.

**Comment by starit1977** [comment]
Any idea when the Plug in will be updated to work with 0.90.5? Like in a month or 2 or early next  year?
